tar czf radar_lightning-ATL.tgz lightning/ATL
tar czf radar_lightning-AC.tgz lightning/AC
tar czf radar_lightning-ARC.tgz lightning/ARC
tar czf radar_lightning-BC-AB.tgz lightning/BC-AB
tar czf radar_lightning-CLDN.tgz lightning/CLDN
tar czf radar_lightning-NAT.tgz lightning/NAT
tar czf radar_lightning-ON-GL.tgz lightning/ON-GL
tar czf radar_lightning-ONT.tgz lightning/ONT
tar czf radar_lightning-PAC.tgz lightning/PAC
tar czf radar_lightning-Prairies.tgz lightning/Prairies
tar czf radar_lightning-QU-AC.tgz lightning/QU-AC
tar czf radar_lightning-QUE.tgz lightning/QUE
tar czf radar_lightning-WRN.tgz lightning/WRN
tar czf radar_lightning-YK-NWT.tgz lightning/YK-NWT
tar czf radar_xft.tgz xft
tar czf radar_atl.tgz atl
tar czf radar_ecan.tgz ecan
tar czf radar_emam.tgz enam
tar czf radar_eusa.tgz eusa
tar czf radar_gedisk11.tgz gedisk11
tar czf radar_gwdisk11.tgz gwdisk11
tar czf radar_nam.tgz nam
tar czf radar_nat.tgz nat
tar czf radar_ont.tgz ont
tar czf radar_pnr.tgz pnr
tar czf radar_pyr.tgz pyr
tar czf radar_que.tgz que
tar czf radar_sigwx.tgz sigwx
tar czf radar_wbi.tgz wbi
tar czf radar_wcan.tgz wcan
tar czf radar_wgj.tgz wgj
tar czf radar_whn.tgz whn
tar czf radar_whk.tgz whk
tar czf radar_wmb.tgz wmb
tar czf radar_wmn.tgz wmn
tar czf radar_wnam.tgz wnam
tar czf radar_wso.tgz wso
tar czf radar_wtp.tgz wtp
tar czf radar_wuj.tgz wuj
tar czf radar_wvy.tgz wvy
tar czf radar_www.tgz www
tar czf radar_xam.tgz xam
tar czf radar_xbe.tgz xbe
tar czf radar_xbu.tgz xbu
tar czf radar_xdr.tgz xdr
tar czf radar_xfw.tgz xfw
tar czf radar_xgo.tgz xgo
tar czf radar_xla.tgz xla
tar czf radar_xmb.tgz xmb
tar czf radar_xme.tgz xme
tar czf radar_xnc.tgz xnc
tar czf radar_xni.tgz xni
tar czf radar_xpg.tgz xpg
tar czf radar_xra.tgz xra
tar czf radar_xsi.tgz xsi
tar czf radar_xsm.tgz xsm
tar czf radar_xss.tgz xss
tar czf radar_xti.tgz xti
tar czf radar_xwl.tgz xwl
